export const RING_SIZE: any = [
  { value: 3, label: '3' },
  { value: 3.5, label: '3.5' },
  { value: 4, label: '4' },
  { value: 4.5, label: '4.5' },
  { value: 5, label: '5' },
  { value: 5.5, label: '5.5' },
  { value: 6, label: '6' },
  { value: 6.5, label: '6.5' },
  { value: 7, label: '7' },
  { value: 7.5, label: '7.5' },
  { value: 8, label: '8' },
  { value: 8.5, label: '8.5' },
  { value: 9, label: '9' },
  { value: 9.5, label: '9.5' },
  { value: 10, label: '10' },
  { value: 10.5, label: '10.5' },
  { value: 11, label: '11' },
  { value: 11.5, label: '11.5' },
  { value: 12, label: '12' },
  { value: 12.5, label: '12.5' },
  { value: 13, label: '13' },
  { value: 13.5, label: '13.5' },
  { value: 14, label: '14' },
  { value: 0, label: 'Other Size' },
];

export const JEWELRY_TYPE: any = [
  {
    title: 'Engagement Rings',
    duration: '50 minutes',
    description: 'Find your ideal ring setting and center diamond or gemstone pairing.',
    image: `/images/ENGAGEMENT_RINGS.webp`,
  },
  {
    title: 'Wedding Bands',
    duration: '50 minutes',
    description: 'Find your ideal Wedding Bands setting and center diamond or gemstone pairing.',
    image: `/images/WEDDING_BANDS.webp`,
  },
  {
    title: 'Bracelet',
    duration: '50 minutes',
    description: 'Find your ideal ring setting and center diamond or gemstone pairing.',
    image: `/images/BRACELET.webp`,
  },
  {
    title: 'Earrings',
    duration: '50 minutes',
    description: 'Find your ideal Earrings setting and center diamond or gemstone pairing.',
    image: `/images/EARRINGS.webp`,
  },
  {
    title: 'Necklace',
    duration: '50 minutes',
    description: 'Find your ideal Necklace setting and center diamond or gemstone pairing.',
    image: `/images/NECKLACE.webp`,
  },
  {
    title: 'Other Jewelry',
    duration: '50 minutes',
    description: 'Find your ideal Other Jewelry setting and center diamond or gemstone pairing.',
    image: `/images/NECKLACE.webp`,
  },
];
